lazada_extra_attrs = {"10675": "<size_body_clothing>0-3 years</size_body_clothing>",
"10671": "<size_body_clothing>0-3 years</size_body_clothing>",
"10672": "<size_body_clothing>0-3 years</size_body_clothing>",
"10673": "<size_body_clothing>0-3 years</size_body_clothing>",
"10674": "<size_body_clothing>0-3 years</size_body_clothing>",
"10632": "<size_body_clothing>0-3 years</size_body_clothing>",
"10640": "<size_body_clothing>0-3 years</size_body_clothing>",
"10641": "<size_body_clothing>0-3 years</size_body_clothing>",
"10642": "<size_body_clothing>0-3 years</size_body_clothing>",
"10643": "<size_body_clothing>0-3 years</size_body_clothing>",
"10644": "<size_body_clothing>0-3 years</size_body_clothing>",
"10633": "<size_body_clothing>0-3 years</size_body_clothing>",
"10650": "<size_body_clothing>0-3 years</size_body_clothing>",
"10646": "<size_body_clothing>0-3 years</size_body_clothing>",
"10647": "<size_body_clothing>0-3 years</size_body_clothing>",
"10648": "<size_body_clothing>0-3 years</size_body_clothing>",
"10649": "<size_body_clothing>0-3 years</size_body_clothing>",
"10653": "<size_body_clothing>0-3 years</size_body_clothing>",
"10654": "<size_body_clothing>0-3 years</size_body_clothing>",
"10652": "<size_body_clothing>0-3 years</size_body_clothing>",
"10655": "<size_body_clothing>0-3 years</size_body_clothing>",
"10638": "<size_body_clothing>0-3 years</size_body_clothing>",
"10636": "<size_body_clothing>0-3 years</size_body_clothing>",
"10637": "<size_body_clothing>0-3 years</size_body_clothing>",
"10635": "<size_body_clothing>0-3 years</size_body_clothing>",
"10657": "<size_body_clothing>0-3 years</size_body_clothing>",
"10656": "<size_body_clothing>0-3 years</size_body_clothing>",
"10665": "<size_body_clothing>0-3 years</size_body_clothing>",
"10666": "<size_body_clothing>0-3 years</size_body_clothing>",
"10667": "<size_body_clothing>0-3 years</size_body_clothing>",
"10668": "<size_body_clothing>0-3 years</size_body_clothing>",
"10669": "<size_body_clothing>0-3 years</size_body_clothing>",
"10664": "<size_body_clothing>0-3 years</size_body_clothing>",
"10661": "<size_body_clothing>0-3 years</size_body_clothing>",
"10659": "<size_body_clothing>0-3 years</size_body_clothing>",
"10662": "<size_body_clothing>0-3 years</size_body_clothing>",
"10660": "<size_body_clothing>0-3 years</size_body_clothing>",
"10629": "<size_body_clothing>0-3 years</size_body_clothing>",
"10623": "<size_body_clothing>0-3 years</size_body_clothing>",
"10625": "<size_body_clothing>0-3 years</size_body_clothing>",
"10624": "<size_body_clothing>0-3 years</size_body_clothing>",
"10626": "<size_body_clothing>0-3 years</size_body_clothing>",
"10628": "<size_body_clothing>0-3 years</size_body_clothing>",
"10627": "<size_body_clothing>0-3 years</size_body_clothing>",
"10582": "<size_body_clothing>0-3 years</size_body_clothing>",
"10591": "<size_body_clothing>0-3 years</size_body_clothing>",
"10592": "<size_body_clothing>0-3 years</size_body_clothing>",
"10593": "<size_body_clothing>0-3 years</size_body_clothing>",
"10594": "<size_body_clothing>0-3 years</size_body_clothing>",
"10595": "<size_body_clothing>0-3 years</size_body_clothing>",
"10596": "<size_body_clothing>0-3 years</size_body_clothing>",
"10583": "<size_body_clothing>0-3 years</size_body_clothing>",
"10584": "<size_body_clothing>0-3 years</size_body_clothing>",
"10602": "<size_body_clothing>0-3 years</size_body_clothing>",
"10598": "<size_body_clothing>0-3 years</size_body_clothing>",
"10599": "<size_body_clothing>0-3 years</size_body_clothing>",
"10600": "<size_body_clothing>0-3 years</size_body_clothing>",
"10601": "<size_body_clothing>0-3 years</size_body_clothing>",
"10605": "<size_body_clothing>0-3 years</size_body_clothing>",
"10606": "<size_body_clothing>0-3 years</size_body_clothing>",
"10604": "<size_body_clothing>0-3 years</size_body_clothing>",
"10607": "<size_body_clothing>0-3 years</size_body_clothing>",
"10587": "<size_body_clothing>0-3 years</size_body_clothing>",
"10589": "<size_body_clothing>0-3 years</size_body_clothing>",
"10588": "<size_body_clothing>0-3 years</size_body_clothing>",
"10586": "<size_body_clothing>0-3 years</size_body_clothing>",
"10609": "<size_body_clothing>0-3 years</size_body_clothing>",
"10608": "<size_body_clothing>0-3 years</size_body_clothing>",
"10617": "<size_body_clothing>0-3 years</size_body_clothing>",
"10618": "<size_body_clothing>0-3 years</size_body_clothing>",
"10619": "<size_body_clothing>0-3 years</size_body_clothing>",
"10620": "<size_body_clothing>0-3 years</size_body_clothing>",
"10621": "<size_body_clothing>0-3 years</size_body_clothing>",
"10616": "<size_body_clothing>0-3 years</size_body_clothing>",
"10613": "<size_body_clothing>0-3 years</size_body_clothing>",
"10611": "<size_body_clothing>0-3 years</size_body_clothing>",
"10614": "<size_body_clothing>0-3 years</size_body_clothing>",
"10612": "<size_body_clothing>0-3 years</size_body_clothing>",
"10579": "<size_body_clothing>0-3 years</size_body_clothing>",
"10574": "<size_body_clothing>0-3 years</size_body_clothing>",
"10577": "<size_body_clothing>0-3 years</size_body_clothing>",
"10578": "<size_body_clothing>0-3 years</size_body_clothing>",
"10576": "<size_body_clothing>0-3 years</size_body_clothing>",
"10046": "<size_diaper>Not Specified</size_diaper>",
"10048": "<diaper_pack_size>Not Specified</diaper_pack_size><size_diaper>Not Specified</size_diaper>",
"10047": "<diaper_pack_size>Not Specified</diaper_pack_size><size_diaper>Not Specified</size_diaper>",
"9994": "<flavor>Not Specified</flavor>",
"9995": "<flavor>Not Specified</flavor>",
"9996": "<flavor>Not Specified</flavor>",
"9997": "<flavor>Not Specified</flavor>",
"9998": "<flavor>Not Specified</flavor>",
"9986": "<volumetric_capacity>Not Specified</volumetric_capacity>",
"9987": "<volumetric_capacity>Not Specified</volumetric_capacity>",
"9985": "<volumetric_capacity>Not Specified</volumetric_capacity>",
"9984": "<volumetric_capacity>Not Specified</volumetric_capacity>",
"9989": "<volumetric_capacity>Not Specified</volumetric_capacity>",
"9990": "<volumetric_capacity>Not Specified</volumetric_capacity>",
"9992": "<volumetric_capacity>Not Specified</volumetric_capacity>",
"9991": "<volumetric_capacity>Not Specified</volumetric_capacity>",
"260": "<water_resistance>Not Specified</water_resistance>",
"9282": "<speed_class>Not Specified</speed_class><storage_capacity_new>Not Specified</storage_capacity_new>",
"9283": "<speed_class>Not Specified</speed_class><storage_capacity_new>Not Specified</storage_capacity_new>",
"9281": "<speed_class>Not Specified</speed_class><storage_capacity_new>Not Specified</storage_capacity_new>",
"11209": "<speed_class>Not Specified</speed_class><storage_capacity_new>Not Specified</storage_capacity_new>",
"253": "<storage_capacity_new>Not Specified</storage_capacity_new>",
"88": "<writing_speed>Not Specified</writing_speed>",
"89": "<fan_dimensions>Not Specified</fan_dimensions>",
"119": "<connectivity_speed>Not Specified</connectivity_speed>",
"127": "<connectivity_speed>Not Specified</connectivity_speed>",
"6216": "<printer_function_type>Not Specified</printer_function_type>",
"6217": "<printer_function_type>Not Specified</printer_function_type>",
"6214": "<printer_function_type>Not Specified</printer_function_type>",
"8916": "<printer_function_type>Not Specified</printer_function_type>",
"6213": "<printer_function_type>Not Specified</printer_function_type>",
"6215": "<printer_function_type>Not Specified</printer_function_type>",
"91": "<storage_capacity_new>Not Specified</storage_capacity_new>",
"114": "<storage_capacity_new>Not Specified</storage_capacity_new>",
"8924": "<storage_capacity_new>Not Specified</storage_capacity_new>",
"6221": "<storage_capacity_new>Not Specified</storage_capacity_new>",
"7306": "<size>{size}</size>",
"7307": "<size>{size}</size>",
"7309": "<size>{size}</size>",
"7310": "<size>{size}</size>",
"7308": "<size>{size}</size>",
"11382": "<size>{size}</size>",
"7315": "<size>{size}</size>",
"7313": "<size>{size}</size>",
"8718": "<size>{size}</size>",
"7319": "<size>{size}</size>",
"7314": "<size>{size}</size>",
"11383": "<size>{size}</size>",
"7312": "<size>{size}</size>",
"8717": "<size>{size}</size>",
"8716": "<size>{size}</size>",
"7291": "<size>{size}</size>",
"11381": "<size>{size}</size>",
"7295": "<size>{size}</size>",
"7288": "<size>{size}</size>",
"7292": "<size>{size}</size>",
"7289": "<size>{size}</size>",
"7287": "<size>{size}</size>",
"7267": "<size>{size}</size>",
"7270": "<size>{size}</size>",
"11379": "<size>{size}</size>",
"7268": "<size>{size}</size>",
"7269": "<size>{size}</size>",
"7274": "<size>{size}</size>",
"7275": "<size>{size}</size>",
"7278": "<size>{size}</size>",
"7280": "<size>{size}</size>",
"11380": "<size>{size}</size>",
"7273": "<size>{size}</size>",
"7282": "<size>{size}</size>",
"7253": "<size>{size}</size>",
"11378": "<size>{size}</size>",
"7251": "<size>{size}</size>",
"7256": "<size>{size}</size>",
"7249": "<size>{size}</size>",
"7254": "<size>{size}</size>",
"7248": "<size>{size}</size>",
"1885": "<size>{size}</size>",
"4155": "<size>{size}</size>",
"4154": "<size>{size}</size>",
"1886": "<size>{size}</size>",
"1877": "<size>{size}</size>",
"1876": "<size>{size}</size>",
"1875": "<size>{size}</size>",
"1878": "<size>{size}</size>",
"1866": "<size>{size}</size>",
"4131": "<size>{size}</size>",
"11360": "<size>{size}</size>",
"4130": "<size>{size}</size>",
"11361": "<size>{size}</size>",
"11384": "<size>{size}</size><fa_pattern>Not Specified</fa_pattern>",
"4292": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4272": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4314": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4266": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4279": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4269": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4277": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4307": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4299": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"1789": "<size>{size}</size><pants_fit_type>Not Specified</pants_fit_type><pants_length>Not Specified</pants_length>",
"4337": "<size>{size}</size><pants_fit_type>Not Specified</pants_fit_type><pants_length>Not Specified</pants_length>",
"1802": "<size>{size}</size><pants_fit_type>Not Specified</pants_fit_type><pants_length>Not Specified</pants_length>",
"4341": "<size>{size}</size><pants_length>Not Specified</pants_length>",
"4213": "<size>{size}</size><collar_type>Not Specified</collar_type><fa_pattern>Not Specified</fa_pattern><sleeves>Not Specified</sleeves>",
"4214": "<size>{size}</size><collar_type>Not Specified</collar_type><fa_pattern>Not Specified</fa_pattern><sleeves>Not Specified</sleeves>",
"11374": "<size>{size}</size><fa_pattern>Not Specified</fa_pattern>",
"11375": "<size>{size}</size><fa_pattern>Not Specified</fa_pattern>",
"11376": "<size>{size}</size><fa_pattern>Not Specified</fa_pattern>",
"11377": "<size>{size}</size>",
"4369": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4370": "<size>{size}</size><pants_fit_type>Not Specified</pants_fit_type><clothing_material>Not Specified</clothing_material>",
"1797": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4385": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4249": "<size>{size}</size><collar_type>Not Specified</collar_type><fa_pattern>Not Specified</fa_pattern>",
"1785": "<size>{size}</size><collar_type>Not Specified</collar_type><fa_pattern>Not Specified</fa_pattern>",
"1799": "<size>{size}</size><fa_pattern>Not Specified</fa_pattern>",
"4196": "<size>{size}</size><collar_type>Not Specified</collar_type><fa_pattern>Not Specified</fa_pattern><sleeves>Not Specified</sleeves>",
"4195": "<size>{size}</size><collar_type>Not Specified</collar_type><fa_pattern>Not Specified</fa_pattern><sleeves>Not Specified</sleeves>",
"11370": "<size>{size}</size><collar_type>Not Specified</collar_type><fa_pattern>Not Specified</fa_pattern><sleeves>Not Specified</sleeves>",
"4347": "<size>{size}</size>",
"1805": "<size>{size}</size><m_underwear_style>Not Specified</m_underwear_style>",
"7241": "<size>{size}</size>",
"4480": "<size>{size}</size>",
"4452": "<size>{size}</size>",
"4453": "<size>{size}</size>",
"4456": "<size>{size}</size>",
"4422": "<size>{size}</size>",
"4424": "<size>{size}</size>",
"4121": "<size>{size}</size>",
"4122": "<size>{size}</size>",
"4123": "<size>{size}</size>",
"11351": "<size>{size}</size>",
"11352": "<size>{size}</size>",
"11353": "<size>{size}</size>",
"11385": "<size>{size}</size>",
"11350": "<size>{size}</size>",
"11358": "<size>{size}</size>",
"11359": "<size>{size}</size>",
"11357": "<size>{size}</size>",
"1818": "<size>{size}</size>",
"11354": "<size>{size}</size>",
"11346": "<size>{size}</size>",
"11366": "<size>{size}</size>",
"11365": "<size>{size}</size>",
"11367": "<size>{size}</size>",
"11368": "<size>{size}</size>",
"11364": "<size>{size}</size>",
"1849": "<size>{size}</size>",
"4160": "<size>{size}</size>",
"1852": "<size>{size}</size>",
"1851": "<size>{size}</size>",
"4152": "<size>{size}</size>",
"3898": "<size>{size}</size>",
"1853": "<size>{size}</size>",
"3899": "<size>{size}</size>",
"11315": "<size>{size}</size>",
"1835": "<size>{size}</size>",
"1830": "<size>{size}</size>",
"1831": "<size>{size}</size>",
"1829": "<size>{size}</size>",
"11314": "<size>{size}</size>",
"4405": "<size>{size}</size><collar_type>Not Specified</collar_type><fa_pattern>Not Specified</fa_pattern>",
"4367": "<size>{size}</size><dress_shape>Not Specified</dress_shape><fa_pattern>Not Specified</fa_pattern><clothing_material>Not Specified</clothing_material>",
"4364": "<size>{size}</size><dress_shape>Not Specified</dress_shape><fa_pattern>Not Specified</fa_pattern><clothing_material>Not Specified</clothing_material>",
"4362": "<size>{size}</size><dress_shape>Not Specified</dress_shape><fa_pattern>Not Specified</fa_pattern><clothing_material>Not Specified</clothing_material>",
"1761": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"11329": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4478": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4469": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4483": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4472": "<size>{size}</size><material_filter>Not Specified</material_filter>",
"4485": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4484": "<size>{size}</size><clothing_material>Not Specified</clothing_material>",
"4339": "<size>{size}</size><pants_fit_type>Not Specified</pants_fit_type><pants_length>Not Specified</pants_length>",
"11336": "<size>{size}</size>",
"11334": "<size>{size}</size>",
"11337": "<size>{size}</size>",
"11338": "<size>{size}</size>",
"11335": "<size>{size}</size>",
"4431": "<size>{size}</size><pants_fit_type>Not Specified</pants_fit_type><pants_length>Not Specified</pants_length><fa_pattern>Not Specified</fa_pattern>",
"11324": "<size>{size}</size>",
"4451": "<size>{size}</size><pants_length>Not Specified</pants_length>",
"1748": "<size>{size}</size><fa_pattern>Not Specified</fa_pattern>",
"4442": "<size>{size}</size><pants_length>Not Specified</pants_length><fa_pattern>Not Specified</fa_pattern>",
"4434": "<size>{size}</size><pants_fit_type>Not Specified</pants_fit_type><pants_length>Not Specified</pants_length><fa_pattern>Not Specified</fa_pattern>",
"11342": "<size>{size}</size>",
"11340": "<size>{size}</size>",
"11343": "<size>{size}</size>",
"11344": "<size>{size}</size>",
"11341": "<size>{size}</size>",
"11328": "<size>{size}</size><fa_pattern>Not Specified</fa_pattern>",
"11326": "<size>{size}</size>",
"11327": "<size>{size}</size><fa_pattern>Not Specified</fa_pattern>",
"4455": "<size>{size}</size><fa_pattern>Not Specified</fa_pattern><skirt_style>Not Specified</skirt_style>",
"4457": "<size>{size}</size><fa_pattern>Not Specified</fa_pattern><skirt_style>Not Specified</skirt_style>",
"4454": "<size>{size}</size><fa_pattern>Not Specified</fa_pattern><skirt_style>Not Specified</skirt_style>",
"1756": "<size>{size}</size>",
"1764": "<size>{size}</size>",
"4510": "<size>{size}</size><fa_pattern>Not Specified</fa_pattern>",
"11322": "<size>{size}</size><collar_type>Not Specified</collar_type><fa_pattern>Not Specified</fa_pattern><sleeves>Not Specified</sleeves>",
"4375": "<size>{size}</size><collar_type>Not Specified</collar_type><fa_pattern>Not Specified</fa_pattern><sleeves>Not Specified</sleeves>",
"1765": "<size>{size}</size><fa_pattern>Not Specified</fa_pattern><sleeves>Not Specified</sleeves>",
"11323": "<size>{size}</size><fa_pattern>Not Specified</fa_pattern><sleeves>Not Specified</sleeves>",
"7236": "<size>{size}</size>",
"12152": "<size>{size}</size>",
"12149": "<size>{size}</size>",
"12137": "<size>{size}</size><bras_types>Not Specified</bras_types><fa_pattern>Not Specified</fa_pattern>",
"12148": "<size>{size}</size>",
"12146": "<size>{size}</size><bras_types>Not Specified</bras_types>",
"12138": "<size>{size}</size><panties_styles>Not Specified</panties_styles><fa_pattern>Not Specified</fa_pattern>",
"12145": "<size>{size}</size>",
"12139": "<size>{size}</size>",
"12141": "<size>{size}</size><shapers_styles>Not Specified</shapers_styles>",
"12143": "<size>{size}</size>",
"4207": "<size>{size}</size>",
"4169": "<size>{size}</size>",
"4198": "<size>{size}</size>",
"4193": "<size>{size}</size>",
"4184": "<size>{size}</size>",
"4206": "<size>{size}</size>",
"11345": "<size>{size}</size>",
"4191": "<size>{size}</size>",
"11305": "<size>{size}</size>",
"4203": "<size>{size}</size>",
"4201": "<size>{size}</size>",
"4135": "<size>{size}</size>",
"11299": "<size>{size}</size>",
"4140": "<size>{size}</size>",
"11300": "<size>{size}</size>",
"4136": "<size>{size}</size>",
"4137": "<size>{size}</size>",
"4144": "<size>{size}</size>",
"11302": "<size>{size}</size>",
"4143": "<size>{size}</size>",
"11311": "<size>{size}</size>",
"11310": "<size>{size}</size>",
"11312": "<size>{size}</size>",
"11306": "<size>{size}</size>",
"1780": "<size>{size}</size>",
"11308": "<size>{size}</size>",
"11307": "<size>{size}</size>",
"11303": "<size>{size}</size>",
"4182": "<size>{size}</size>",
"4183": "<size>{size}</size>",
"4180": "<size>{size}</size>",
"11320": "<size>{size}</size>",
"11319": "<size>{size}</size>",
"11321": "<size>{size}</size>",
"11317": "<size>{size}</size>",
"1498": "<color_hb>Not Specified</color_hb>",
"1500": "<color_hb>Not Specified</color_hb>",
"1501": "<color_hb>Not Specified</color_hb>",
"1504": "<color_hb>Not Specified</color_hb>",
"1506": "<color_hb>Not Specified</color_hb>",
"1519": "<color_hb>Not Specified</color_hb>",
"1520": "<color_hb>Not Specified</color_hb>",
"1521": "<color_hb>Not Specified</color_hb>",
"1522": "<color_hb>Not Specified</color_hb>",
"1539": "<color_hb>Not Specified</color_hb>",
"1542": "<color_hb>Not Specified</color_hb>",
"1658": "<color_hb>Not Specified</color_hb>",
"1705": "<color_hb>Not Specified</color_hb>",
"1706": "<color_hb>Not Specified</color_hb>",
"1721": "<units>Not Specified</units>",
"1723": "<units>Not Specified</units>",
"1724": "<units>Not Specified</units>",
"5062": "<bedding_size_2>Not Specified</bedding_size_2>",
"458": "<filling>Not Specified</filling>",
"5031": "<filling>Not Specified</filling>",
"465": "<filling>Not Specified</filling>",
"979": "<holding_capacity>Not Specified</holding_capacity>",
"980": "<holding_capacity>Not Specified</holding_capacity>",
"978": "<holding_capacity>Not Specified</holding_capacity>",
"981": "<holding_capacity>Not Specified</holding_capacity>",
"1279": "<paper_size>Not Specified</paper_size>",
"5326": "<paper_size>Not Specified</paper_size>",
"1281": "<paper_size>Not Specified</paper_size>",
"1280": "<paper_size>Not Specified</paper_size>",
"6416": "<horsepower>Not Specified</horsepower><type_air_conditioner>Not Specified</type_air_conditioner>",
"9589": "<horsepower>Not Specified</horsepower><type_air_conditioner>Not Specified</type_air_conditioner>",
"9588": "<horsepower>Not Specified</horsepower><type_air_conditioner>Not Specified</type_air_conditioner>",
"9584": "<horsepower>Not Specified</horsepower>",
"9585": "<horsepower>Not Specified</horsepower>",
"9586": "<horsepower>Not Specified</horsepower>",
"9587": "<horsepower>Not Specified</horsepower>",
"6415": "<horsepower>Not Specified</horsepower><type_air_conditioner>Not Specified</type_air_conditioner>",
"339": "<number_of_hobs>Not Specified</number_of_hobs>",
"340": "<number_of_hobs>Not Specified</number_of_hobs>",
"345": "<number_of_hobs>Not Specified</number_of_hobs><wattage_ha>Not Specified</wattage_ha>",
"6490": "<wattage_ha>Not Specified</wattage_ha>",
"6495": "<wattage_ha>Not Specified</wattage_ha>",
"6472": "<capacity>Not Specified</capacity>",
"6470": "<capacity>Not Specified</capacity>",
"6471": "<capacity>Not Specified</capacity>",
"6476": "<auto_defrost>Not Specified</auto_defrost><capacity>Not Specified</capacity>",
"6474": "<auto_defrost>Not Specified</auto_defrost><capacity>Not Specified</capacity>",
"6475": "<auto_defrost>Not Specified</auto_defrost><capacity>Not Specified</capacity>",
"6535": "<capacity>Not Specified</capacity>",
"6504": "<capacity>Not Specified</capacity>",
"6502": "<capacity>Not Specified</capacity>",
"9609": "<capacity>Not Specified</capacity>",
"6503": "<capacity>Not Specified</capacity>",
"6512": "<nofrost_system>Not Specified</nofrost_system><capacity>Not Specified</capacity>",
"6513": "<nofrost_system>Not Specified</nofrost_system><capacity>Not Specified</capacity>",
"6514": "<nofrost_system>Not Specified</nofrost_system><capacity>Not Specified</capacity>",
"6517": "<nofrost_system>Not Specified</nofrost_system><capacity>Not Specified</capacity>",
"6518": "<nofrost_system>Not Specified</nofrost_system><capacity>Not Specified</capacity>",
"6515": "<nofrost_system>Not Specified</nofrost_system><capacity>Not Specified</capacity>",
"6536": "<capacity>Not Specified</capacity>",
"356": "<capacity>Not Specified</capacity>",
"289": "<capacity>Not Specified</capacity>",
"290": "<capacity>Not Specified</capacity>",
"278": "<size_of_jug>Other</size_of_jug>",
"279": "<size_of_jug>Other</size_of_jug>",
"6586": "<capacity>Not Specified</capacity>",
"316": "<capacity>Not Specified</capacity>",
"6585": "<capacity>Not Specified</capacity>",
"312": "<capacity>Not Specified</capacity>",
"313": "<capacity>Not Specified</capacity>",
"6584": "<capacity>Not Specified</capacity>",
"314": "<capacity>Not Specified</capacity>",
"315": "<capacity>Not Specified</capacity>",
"11183": "<compatibility_by_model>Other</compatibility_by_model>",
"11551": "<brand_compatibility>Not Specified</brand_compatibility>",
"11552": "<brand_compatibility>Not Specified</brand_compatibility>",
"11169": "<compatibility_by_model>Other</compatibility_by_model>",
"11190": "<powerbank_capacity>Not Specified</powerbank_capacity>",
"11170": "<compatibility_by_model>Other</compatibility_by_model>",
"11178": "<compatibility_by_model>Other</compatibility_by_model>",
"11181": "<compatibility_by_model>Other</compatibility_by_model>",
"11177": "<compatibility_by_model>Other</compatibility_by_model>",
"3252": "<size_wear>Not Specified</size_wear>",
"3253": "<size_wear>Not Specified</size_wear>",
"3254": "<size_wear>Not Specified</size_wear>",
"3257": "<pack_size>Not Specified</pack_size>",
"11831": "<size>{size}</size>",
"11811": "<size>{size}</size>",
"11828": "<size>{size}</size>",
"11813": "<size>{size}</size>",
"11825": "<size>{size}</size>",
"11822": "<size>{size}</size>",
"11826": "<size>{size}</size>",
"11829": "<size>{size}</size>",
"11830": "<size>{size}</size>",
"11755": "<size>{size}</size>",
"11756": "<size>{size}</size>",
"11757": "<size>{size}</size>",
"11758": "<size>{size}</size>",
"11759": "<size>{size}</size>",
"11760": "<size>{size}</size>",
"11761": "<size>{size}</size>",
"11762": "<size>{size}</size>",
"11798": "<size>{size}</size>",
"11763": "<size>{size}</size>",
"11764": "<size>{size}</size>",
"11803": "<size>{size}</size>",
"11805": "<size>{size}</size>",
"11807": "<size>{size}</size>",
"11809": "<size>{size}</size>",
"11751": "<size>{size}</size>",
"11729": "<size>{size}</size>",
"11741": "<size>{size}</size>",
"11740": "<size>{size}</size>",
"11737": "<size>{size}</size>",
"11731": "<size>{size}</size>",
"11739": "<size>{size}</size>",
"11742": "<size>{size}</size>",
"11736": "<size>{size}</size>",
"11747": "<size>{size}</size>",
"11749": "<size>{size}</size>",
"11697": "<size>{size}</size>",
"11698": "<size>{size}</size>",
"11704": "<size>{size}</size>",
"11707": "<size>{size}</size>",
"11709": "<size>{size}</size>",
"11711": "<size>{size}</size>",
"11713": "<size>{size}</size>",
"11715": "<size>{size}</size>",
"11722": "<size>{size}</size>",
"11717": "<size>{size}</size>",
"11719": "<size>{size}</size>",
"11723": "<size>{size}</size>",
"11724": "<size>{size}</size>",
"11726": "<size>{size}</size>",
"11727": "<size>{size}</size>",
"11863": "<size>{size}</size>",
"11866": "<size>{size}</size>",
"11864": "<size>{size}</size>",
"11868": "<size>{size}</size>",
"11913": "<size>{size}</size>",
"11867": "<size>{size}</size>",
"11865": "<size>{size}</size>",
"11869": "<size>{size}</size>",
"4862": "<size>{size}</size>",
"11694": "<size>{size}</size>",
"11695": "<size>{size}</size>",
"11693": "<size>{size}</size>",
"4859": "<size>{size}</size>",
"4861": "<size>{size}</size>",
"11696": "<size>{size}</size>",
"11861": "<size>{size}</size>",
"4867": "<size>{size}</size>",
"4866": "<size>{size}</size>",
"11862": "<size>{size}</size>",
"11852": "<size>{size}</size>",
"4851": "<size>{size}</size>",
"4856": "<size>{size}</size>",
"11855": "<size>{size}</size>",
"4854": "<size>{size}</size>",
"4850": "<size>{size}</size>",
"4849": "<size>{size}</size>",
"4857": "<size>{size}</size>",
"11857": "<size>{size}</size>",
"4847": "<size>{size}</size>",
"11856": "<size>{size}</size>",
"11858": "<size>{size}</size>",
"11859": "<size>{size}</size>",
"11860": "<size>{size}</size>",
"4855": "<size>{size}</size>",
"11834": "<size>{size}</size>",
"11839": "<size>{size}</size>",
"11835": "<size>{size}</size>",
"11841": "<size>{size}</size>",
"11909": "<size>{size}</size>",
"11840": "<size>{size}</size>",
"11836": "<size>{size}</size>",
"11842": "<size>{size}</size>",
"4828": "<size>{size}</size>",
"4830": "<size>{size}</size>",
"11847": "<size>{size}</size>",
"11848": "<size>{size}</size>",
"11845": "<size>{size}</size>",
"4822": "<size>{size}</size>",
"4826": "<size>{size}</size>",
"11851": "<size>{size}</size>",
"11911": "<size>{size}</size>",
"11850": "<size>{size}</size>",
"11832": "<size>{size}</size>",
"11680": "<size>{size}</size>",
"11833": "<size>{size}</size>",
"11681": "<size>{size}</size>",
"4825": "<size>{size}</size>",
"4821": "<size>{size}</size>",
"4831": "<size>{size}</size>",
"11674": "<size>{size}</size>",
"4827": "<size>{size}</size>",
"4819": "<size>{size}</size>",
"4818": "<size>{size}</size>",
"4832": "<size>{size}</size>",
"11676": "<size>{size}</size>",
"4813": "<size>{size}</size>",
"11675": "<size>{size}</size>",
"11677": "<size>{size}</size>",
"11678": "<size>{size}</size>",
"11679": "<size>{size}</size>",
"4829": "<size>{size}</size>",
"155": "<bluetooth>Not Specified</bluetooth>",
"11392": "<bluetooth>Not Specified</bluetooth>",
"8364": "<bluetooth>Not Specified</bluetooth>",
"156": "<bluetooth>Not Specified</bluetooth>",
"11393": "<bluetooth>Not Specified</bluetooth>",
"8497": "<ptb_speaker_features>Not Specified</ptb_speaker_features><bluetooth>Not Specified</bluetooth>",
"225": "<platform>Not Specified</platform>",
"11501": "<cable_type_tagg>Not Specified</cable_type_tagg>",
"11496": "<receiver_type>Not Specified</receiver_type>",
"200": "<display_size_tv>Not Specified</display_size_tv><curved_tv>Not Specified</curved_tv><smart_tv>Not Specified</smart_tv><tv_resolution>Not Specified</tv_resolution><tv_technology>Not Specified</tv_technology>",
"201": "<display_size_tv>Not Specified</display_size_tv><curved_tv>Not Specified</curved_tv><smart_tv>Not Specified</smart_tv><tv_resolution>Not Specified</tv_resolution><tv_technology>Not Specified</tv_technology>",
"202": "<display_size_tv>Not Specified</display_size_tv><curved_tv>Not Specified</curved_tv><smart_tv>Not Specified</smart_tv><tv_resolution>Not Specified</tv_resolution><tv_technology>Not Specified</tv_technology>",
"11474": "<display_size_tv>Not Specified</display_size_tv><curved_tv>Not Specified</curved_tv><smart_tv>Not Specified</smart_tv><tv_resolution>Not Specified</tv_resolution><tv_technology>Not Specified</tv_technology>",
"203": "<display_size_tv>Not Specified</display_size_tv><curved_tv>Not Specified</curved_tv><smart_tv>Not Specified</smart_tv><tv_resolution>Not Specified</tv_resolution><tv_technology>Not Specified</tv_technology>",
"204": "<display_size_tv>Not Specified</display_size_tv><curved_tv>Not Specified</curved_tv><smart_tv>Not Specified</smart_tv><tv_resolution>Not Specified</tv_resolution><tv_technology>Not Specified</tv_technology>",
"194": "<projector_types>Not Specified</projector_types>",
"8426": "<os_compatibility>Not Specified</os_compatibility>",
"11492": "<smartwear_size>Not Specified</smartwear_size>",
"8425": "<smartwear_model_compa>Not Specified</smartwear_model_compa><os_compatibility>Not Specified</os_compatibility>",
"11478": "<smartwear_size>Not Specified</smartwear_size>",
"9424": "<suitcase_size>Not Specified</suitcase_size>",
"9406": "<laptop_size>Not Specified</laptop_size>",
"1957": "<suitcase_size>Not Specified</suitcase_size>",
"1953": "<suitcase_size>Not Specified</suitcase_size>",
"7448": "<Test__Att__902PM>Not Specified</Test__Att__902PM>",
"8637": "<frame_color>Not Specified</frame_color>",
"8636": "<frame_color>Not Specified</frame_color>",
"8634": "<frame_color>Not Specified</frame_color>",
"8633": "<frame_color>Not Specified</frame_color>",
"8631": "<frame_color>Not Specified</frame_color>",
"8630": "<frame_color>Not Specified</frame_color>",
"8656": "<chain_size>One Size</chain_size>",
"8657": "<chain_size>One Size</chain_size>",
"8658": "<chain_size>One Size</chain_size>",
"8659": "<chain_size>One Size</chain_size>",
"8660": "<chain_size>One Size</chain_size>",
"8661": "<chain_size>One Size</chain_size>",
"8662": "<chain_size>One Size</chain_size>",
"8641": "<bangle_size>One Size</bangle_size>",
"8642": "<bangle_size>One Size</bangle_size>",
"8643": "<bangle_size>One Size</bangle_size>",
"8644": "<bangle_size>One Size</bangle_size>",
"8645": "<bracelet_size>One Size</bracelet_size>",
"8646": "<bracelet_size>One Size</bracelet_size>",
"8647": "<bracelet_size>One Size</bracelet_size>",
"8648": "<bracelet_size>One Size</bracelet_size>",
"8649": "<bracelet_size>One Size</bracelet_size>",
"8651": "<earring_size>One Size</earring_size>",
"8652": "<earring_size>One Size</earring_size>",
"8653": "<earring_size>One Size</earring_size>",
"8654": "<earring_size>One Size</earring_size>",
"8700": "<watch_strap_color>Multicolor</watch_strap_color>",
"8701": "<watch_strap_color>Multicolor</watch_strap_color>",
"8702": "<watch_strap_color>Multicolor</watch_strap_color>",
"8687": "<ring_size>{size}</ring_size>",
"8692": "<ring_size>{size}</ring_size>",
"8665": "<ring_size>{size}</ring_size>",
"8663": "<ring_size>{size}</ring_size>",
"8681": "<ring_size>{size}</ring_size>"}


def get_extra_attrs(category_id):
    return '<root>'+lazada_extra_attrs.get(str(category_id),'')+'</root>'


def testXml():
    from lxml import etree
    for k, v in lazada_extra_attrs.items():
        print(v.format(size='XL'))
        print("------------------------------")
        etree.XML('<root>' + v.format(size='XL').strip() + '</root>')

if __name__ == "__main__":
    testXml()

