colors = ["Abyss",
"Acid blue",
"Acid green",
"Aero",
"Aero blue",
"African purple",
"Air Force blue",
"Alabama crimson",
"Alaska blue",
"Alice blue",
"Alizarin crimson",
"Alloy orange",
"Almond",
"Alpenglow",
"Amaranth",
"Amaranth pink",
"Amarillo",
"Amazon",
"Amber",
"Amber gold",
"Ambrosial Crush",
"American rose",
"Amethyst",
"Amphora",
"Android green",
"Angora",
"Anti-flash white",
"Antique Black",
"Antique Gold",
"Antique brass",
"Antique bronze",
"Antique fuchsia",
"Antique ruby",
"Antique silver",
"Antique white",
"Apple",
"Apple green",
"Apricot",
"Aqua",
"Aqua blue",
"Aquamarine",
"Arctic blue",
"Army",
"Army green",
"Arsenic",
"Arylide yellow",
"Ash",
"Ash black",
"Ash grey",
"Asparagus",
"Asphalt",
"Aster",
"Atomic",
"Atomic tangerine",
"Auburn",
"Aureolin",
"AuroMetalSaurus",
"Avocado",
"Azure",
"Azure mist",
"B'dazzled blue",
"Baby Doll",
"Baby blue",
"Baby blue eyes",
"Baby pink",
"Baby powder",
"Baker-Miller pink",
"Ball blue",
"Baltic",
"Banana",
"Banana Mania",
"Banana yellow",
"Barbie pink",
"Barn red",
"Battleship grey",
"Bay",
"Bazaar",
"Beach",
"Beau blue",
"Beaver",
"Beige",
"Bejeweled",
"Berry",
"Big dip o'ruby",
"Birch",
"Biscuit",
"Bisque",
"Bistre",
"Bistre brown",
"Bitter lemon",
"Bitter lime",
"Bittersweet",
"Bittersweet shimmer",
"Black",
"Black bean",
"Black brown",
"Black fuchsia",
"Black gray",
"Black leather jacket",
"Black olive",
"Black white",
"Black-purple",
"Blackberry",
"Blackberry Wine",
"Blackwatch",
"Blanched almond",
"Blast-off bronze",
"Bleu de France",
"Blizzard Blue",
"Blond",
"Blossom",
"Blue",
"Blue Bell",
"Blue Chocolate",
"Blue Light Wash",
"Blue Pearl",
"Blue Wash",
"Blue Wing Teal",
"Blue sapphire",
"Blue yonder",
"Blue-Cream",
"Blue-gray",
"Blue-green",
"Blue-violet",
"Blueberry",
"Bluebonnet",
"Bluegrass",
"Blush",
"Bole",
"Bondi blue",
"Bone",
"Bottle green",
"Boysenberry",
"Brandeis blue",
"Brass",
"Brick",
"Brick red",
"Bright Orange",
"Bright blue",
"Bright cerulean",
"Bright green",
"Bright lavender",
"Bright maroon",
"Bright navy blue",
"Bright pink",
"Bright red",
"Bright turquoise",
"Bright ube",
"Brilliant lavender",
"Brilliant rose",
"Brink pink",
"British racing green",
"Bronze",
"Bronze Yellow",
"Brown",
"Brown Sugar",
"Brown-Cream",
"Brown-nose",
"Brunswick green",
"Bubble gum",
"Bubblegum Pink",
"Bubbles",
"Buck",
"Bud green",
"Buff",
"Bulgarian rose",
"Burgundy",
"Burgundy Metallic",
"Burgundy Pearl",
"Burlywood",
"Burnt orange",
"Burnt sienna",
"Burnt umber",
"Butter",
"Buttercup",
"Byzantine",
"Byzantium",
"CG Blue",
"CG Red",
"Cadet",
"Cadet blue",
"Cadet grey",
"Cadmium green",
"Cadmium orange",
"Cadmium red",
"Cadmium yellow",
"Cafe",
"Cal Poly green",
"Calm",
"Cambridge Blue",
"Camel",
"Camel brown",
"Camellia Rose",
"Cameo pink",
"Camo",
"Camouflage",
"Camouflage green",
"Canary yellow",
"Cancun",
"Candy apple red",
"Candy pink",
"Capri",
"Caput mortuum",
"Carafe",
"Carbon",
"Carbon Fiber Black",
"Cardinal",
"Caribbean green",
"Carmine",
"Carmine pink",
"Carmine red",
"Carnation pink",
"Carnelian",
"Carolina blue",
"Carrot orange",
"Castleton green",
"Catalina blue",
"Catawba",
"Cedar Chest",
"Ceil",
"Celadon",
"Celadon blue",
"Celadon green",
"Celery",
"Celery green",
"Celeste",
"Celestial blue",
"Cement",
"Cerise",
"Cerise pink",
"Cerulean",
"Cerulean blue",
"Cerulean frost",
"Chalk Blue",
"Chamoisee",
"Champagne",
"Champagne-Orange",
"Charcoal",
"Charleston green",
"Charm pink",
"Chartreuse",
"Checkered Red",
"Checkered White",
"Cheddar Yellow",
"Cheers",
"Cheetah",
"Cheetah print",
"Cherry",
"Cherry Pink",
"Cherry blossom pink",
"Chestnut",
"Chili",
"Chili Pepper",
"Chill",
"China pink",
"China rose",
"Chinchilla",
"Chinese red",
"Chinese violet",
"Chocolate",
"Chocolate brown",
"Chrome yellow",
"Cinereous",
"Cinnabar",
"Cinnamon",
"Citadel",
"Citrine",
"Citron",
"Claret",
"Classic rose",
"Clear",
"Clear Beige",
"Clear Blue",
"Clear Gray",
"Clear Green",
"Clear Green Pearl",
"Clear Pink",
"Clear Pink Pearl",
"Cloud Burst",
"Clover",
"Coal",
"Coast",
"Cobalt",
"Cobblestone",
"Cocoa",
"Cocoa Bean",
"Cocoa brown",
"Coconut",
"Coffee",
"Coffee Bean Silver Pink",
"Columbia blue",
"Columblue",
"Concrete",
"Congo pink",
"Cool black",
"Cool grey",
"Cool white",
"Copper",
"Copper penny",
"Copper red",
"Copper rose",
"Coquelicot",
"Coral",
"Coral green",
"Coral pink",
"Coral red",
"Cordovan",
"Corn",
"Cornell Red",
"Cornflower",
"Cornflower blue",
"Cornsilk",
"Cosmic latte",
"Cotton candy",
"Cream",
"Creme",
"Crimson",
"Crimson glory",
"Crushed Berry",
"Crystal Ball",
"Crystal Clear",
"Currant",
"Cyan",
"Cyber grape",
"Cyber yellow",
"Daffodil",
"Dahlia",
"Dandelion",
"Dark Blue Pearl",
"Dark army green",
"Dark blond",
"Dark blue",
"Dark blue-gray",
"Dark blue-silver grey",
"Dark blue-sky blue",
"Dark brown",
"Dark brown-army green",
"Dark brown-black",
"Dark byzantium",
"Dark candy apple red",
"Dark cerulean",
"Dark chestnut",
"Dark coffee",
"Dark coral",
"Dark cyan",
"Dark electric blue",
"Dark goldenrod",
"Dark gray",
"Dark green",
"Dark grey",
"Dark imperial blue",
"Dark jungle green",
"Dark khaki",
"Dark lava",
"Dark lavender",
"Dark liver",
"Dark magenta",
"Dark midnight blue",
"Dark moss green",
"Dark olive green",
"Dark orange",
"Dark orchid",
"Dark pastel blue",
"Dark pastel green",
"Dark pastel purple",
"Dark pastel red",
"Dark pink",
"Dark plum",
"Dark powder blue",
"Dark purple",
"Dark raspberry",
"Dark red",
"Dark red-army green",
"Dark red-black",
"Dark salmon",
"Dark scarlet",
"Dark sea green",
"Dark sienna",
"Dark sky blue",
"Dark slate blue",
"Dark slate gray",
"Dark spring green",
"Dark tan",
"Dark tangerine",
"Dark taupe",
"Dark terra cotta",
"Dark turquoise",
"Dark vanilla",
"Dark violet",
"Dark yellow",
"Dartmouth green",
"Davy's grey",
"Daybreak",
"Debian red",
"Deep",
"Deep Space Sparkle",
"Deep Taupe",
"Deep Teal",
"Deep Tuscan red",
"Deep carmine",
"Deep carmine pink",
"Deep carrot orange",
"Deep cerise",
"Deep champagne",
"Deep chestnut",
"Deep coffee",
"Deep fuchsia",
"Deep jungle green",
"Deep lemon",
"Deep lilac",
"Deep magenta",
"Deep mauve",
"Deep moss green",
"Deep peach",
"Deep pink",
"Deep ruby",
"Deep saffron",
"Deep sky blue",
"Deer",
"Denim",
"Denim blue",
"Desert",
"Desert sand",
"Desire",
"Diamond",
"Dill",
"Dillweed",
"Dim gray",
"Dinar",
"Dirt",
"Dodger blue",
"Dogwood rose",
"Dollar bill",
"Donkey Brown",
"Drab",
"Dreamscape",
"Driftwood",
"Duke blue",
"Dust storm",
"Dusty Blue",
"Dusty Cedar",
"Dusty Pink",
"Dutch white",
"Earth",
"Earth yellow",
"Ebony",
"Ecru",
"Eggplant",
"Eggshell",
"Egyptian blue",
"Electric blue",
"Electric crimson",
"Electric cyan",
"Electric green",
"Electric indigo",
"Electric lavender",
"Electric lime",
"Electric purple",
"Electric ultramarine",
"Electric violet",
"Electric yellow",
"Emerald",
"Eminence",
"Emotion",
"English green",
"English lavender",
"English red",
"English violet",
"Envy",
"Eton blue",
"Eucalyptus",
"Fabulous",
"Fallow",
"Falu red",
"Fandango",
"Fandango pink",
"Fashion fuchsia",
"Fatigue",
"Fawn",
"Feldgrau",
"Feldspar",
"Fern",
"Fern green",
"Ferrari Red",
"Field drab",
"Fiesta",
"Fire engine red",
"Firebrick",
"Flame",
"Flame red-light khaki",
"Flamingo",
"Flamingo pink",
"Flat Dark Earth",
"Flattery",
"Flavescent",
"Flax",
"Flint",
"Flirt",
"Floral",
"Floral print",
"Floral white",
"Fluorescence green",
"Fluorescent blue",
"Fluorescent green",
"Fluorescent orange",
"Fluorescent pink",
"Fluorescent rose",
"Fluorescent yellow",
"Flush",
"Fog",
"Folly",
"Forest",
"Forest camouflage",
"Forest green",
"Forget Me Not",
"French beige",
"French bistre",
"French blue",
"French lilac",
"French lime",
"French mauve",
"French puce",
"French raspberry",
"French rose",
"French sky blue",
"French wine",
"Fresh Air",
"Frost White",
"Fuchsia",
"Fuchsia pink",
"Fuchsia rose",
"Fuchsia-Black",
"Fulvous",
"Fushcia",
"Fuzzy Wuzzy",
"Gainsboro",
"Gamboge",
"Garnet",
"Generic viridian",
"Ghost white",
"Giants orange",
"Ginger",
"Giraffe",
"Glaucous",
"Glistening Sun",
"Glitter",
"Gold",
"Gold Fusion",
"Golden",
"Golden brown",
"Golden poppy",
"Golden yellow",
"Goldenrod",
"Goldfish",
"Goldmine",
"Gradient black",
"Granite",
"Granny Smith Apple",
"Grape",
"Graphite",
"Grass green",
"Gray",
"Gray-asparagus",
"Gray-blue",
"Green",
"Green Apple",
"Green Eyes",
"Green Flash",
"Green Pearl",
"Green light",
"Green plaid",
"Green-yellow",
"Grey",
"Grey White",
"Grey Wolf",
"Greyish white",
"Grullo",
"Gumdrop",
"Guppie green",
"Han blue",
"Han purple",
"Hansa yellow",
"Harbor",
"Harlequin",
"Harvard crimson",
"Harvest gold",
"Haze",
"Heart Gold",
"Heather",
"Heather Gray",
"Heather grey",
"Heliconia",
"Heliotrope",
"Hibiscus",
"Highlander",
"Highlight",
"Hollywood cerise",
"Honey",
"Honeydew",
"Honolulu blue",
"Hot magenta",
"Hot pink",
"Humus",
"Hunter",
"Hunter green",
"Iceberg",
"Iced Coffee",
"Icterine",
"Illuminating Emerald",
"Imperial",
"Imperial blue",
"Imperial purple",
"Imperial red",
"Incense",
"Inchworm",
"Independence",
"India green",
"Indian red",
"Indian yellow",
"Indigo",
"Indigo dye",
"Ink blue",
"Iridescent",
"Iris",
"Irish green",
"Irresistible",
"Isabelline",
"Islamic green",
"Italian sky blue",
"Ivory",
"J.Navy",
"Jade",
"Japanese indigo",
"Japanese violet",
"Jasmine",
"Jasper",
"Java",
"Jazzberry jam",
"Jelly Bean",
"Jet",
"Jojoba",
"Jonquil",
"June bud",
"Jungle green",
"KU Crimson",
"Kelly",
"Kelly green",
"Kenyan copper",
"Keppel",
"Khaki",
"Khaki Beige",
"Khaki Green",
"Kiwi",
"Kobe",
"Kobi",
"Kombu green",
"La Salle Green",
"Lake blue",
"Lake green",
"Languid lavender",
"Lapis lazuli",
"Laser Lemon",
"Latte",
"Laurel green",
"Lava",
"Lavender",
"Lavender Fog",
"Lavender blue",
"Lavender blush",
"Lavender gray",
"Lavender indigo",
"Lavender magenta",
"Lavender mist",
"Lavender pink",
"Lavender purple",
"Lavender rose",
"Lawn green",
"Lead",
"Leaf",
"Lemon",
"Lemon chiffon",
"Lemon curry",
"Lemon glacier",
"Lemon lime",
"Lemon meringue",
"Lemon yellow",
"Leopard",
"Leopard print",
"Lettuce Green",
"Liberty",
"Licorice",
"Light Blue Pearl",
"Light Thulian pink",
"Light apricot",
"Light beige",
"Light blond",
"Light blue",
"Light brown",
"Light carmine pink",
"Light coffee",
"Light coral",
"Light cornflower blue",
"Light crimson",
"Light cyan",
"Light fuchsia pink",
"Light goldenrod yellow",
"Light gray",
"Light green",
"Light grey",
"Light khaki",
"Light leopard",
"Light medium orchid",
"Light moss green",
"Light orchid",
"Light pastel purple",
"Light pink",
"Light purple",
"Light red ochre",
"Light rose",
"Light salmon",
"Light salmon pink",
"Light sea green",
"Light sky blue",
"Light slate gray",
"Light steel blue",
"Light tan",
"Light taupe",
"Light wine red",
"Light yellow",
"Lilac",
"Lilac Grey",
"Lime",
"Lime green",
"Limerick",
"Limpit Shell",
"Lincoln green",
"Linen",
"Lion",
"Little boy blue",
"Liver",
"Liver chestnut",
"Livid",
"Loden",
"Lollipop",
"Lumber",
"Lust",
"Lynx",
"MSU Green",
"Magenta",
"Magenta haze",
"Magic mint",
"Magnolia",
"Mahogany",
"Maize",
"Majorelle Blue",
"Malachite",
"Manatee",
"Mandarin",
"Mango Tango",
"Mantis",
"Maple",
"Marble",
"Mardi Gras",
"Margarita",
"Marine",
"Maroon",
"Matte Black",
"Matte White",
"Mauve",
"Mauve taupe",
"Mauvelous",
"May green",
"Maya blue",
"Meat brown",
"Mediterranean Blue",
"Medium Persian blue",
"Medium Tuscan red",
"Medium aquamarine",
"Medium blond",
"Medium blue",
"Medium brown",
"Medium candy apple red",
"Medium carmine",
"Medium champagne",
"Medium electric blue",
"Medium jungle green",
"Medium lavender magenta",
"Medium orchid",
"Medium purple",
"Medium red-violet",
"Medium ruby",
"Medium sea green",
"Medium sky blue",
"Medium slate blue",
"Medium spring bud",
"Medium spring green",
"Medium taupe",
"Medium turquoise",
"Medium vermilion",
"Medium violet-red",
"Mellow apricot",
"Mellow yellow",
"Melon",
"Merlot",
"Metallic Bronze",
"Metallic Gold",
"Metallic Onyx",
"Metallic Pink",
"Metallic Purple",
"Metallic Red",
"Metallic Seaweed",
"Metallic Silver",
"Metallic Sunburst",
"Meteorite",
"Mexican pink",
"Mica",
"Midnight",
"Midnight blue",
"Midnight green",
"Midori",
"Migration",
"Mikado yellow",
"Milk Chocolate",
"Milk white",
"Mini Black/White Zebra",
"Mint",
"Mint cream",
"Mint green",
"Misty rose",
"Moccasin",
"Mocha",
"Mode beige",
"Moonstone blue",
"Mordant red 19",
"Moss green",
"Mother of Pearl",
"Mountain Meadow",
"Mountbatten pink",
"Mughal green",
"Mulberry",
"Multicolor",
"Multicolored",
"Mustard",
"Myrtle green",
"Nacarat",
"Nadeshiko pink",
"Napier green",
"Naples yellow",
"Native Earth",
"Natural",
"Navajo white",
"Navy",
"Navy blue",
"Navy blue-lake blue",
"Navy purple",
"Nectarine",
"Neon Carrot",
"Neon blue",
"Neon fuchsia",
"Neon green",
"Neon orange",
"Neon pink",
"Neon red",
"Neon yellow",
"New Car",
"New York pink",
"Newspaper",
"Nickel",
"Night",
"Nile Blue",
"Noche",
"Non-photo blue",
"North Texas Green",
"Nude",
"Nutmeg",
"Nyanza",
"OU Crimson Red",
"Oakmoss",
"Oatmeal",
"Ocean",
"Ocean Boat Blue",
"Ocean blue",
"Oceanberry",
"Ochre",
"Off white",
"Off-white",
"Office green",
"Old burgundy",
"Old gold",
"Old lace",
"Old lavender",
"Old mauve",
"Old moss green",
"Old rose",
"Old silver",
"Olive",
"Olive Branch",
"Olive Drab",
"Olive green",
"Olive green black",
"Olivine",
"Onyx",
"Opera mauve",
"Orange",
"Orange light",
"Orange peel",
"Orange plaid",
"Orange-red",
"Orchid",
"Orchid pink",
"Orioles orange",
"Orion",
"Otter brown",
"Outer Space",
"Outrageous Orange",
"Oxford",
"Oxford Blue",
"Oyster",
"Pacific",
"Pakistan green",
"Palace Blue",
"Palatinate blue",
"Palatinate purple",
"Pale aqua",
"Pale blue",
"Pale brown",
"Pale carmine",
"Pale cerulean",
"Pale chestnut",
"Pale copper",
"Pale cornflower blue",
"Pale gold",
"Pale goldenrod",
"Pale green",
"Pale lavender",
"Pale magenta",
"Pale pink",
"Pale plum",
"Pale red-violet",
"Pale robin egg blue",
"Pale silver",
"Pale spring bud",
"Pale taupe",
"Pale turquoise",
"Pale violet-red",
"Pansy purple",
"Paolo Veronese green",
"Papaya whip",
"Paris Green",
"Pastel blue",
"Pastel brown",
"Pastel gray",
"Pastel green",
"Pastel magenta",
"Pastel orange",
"Pastel pink",
"Pastel purple",
"Pastel red",
"Pastel violet",
"Pastel yellow",
"Patriarch",
"Payne's grey",
"Peach",
"Peach Echo",
"Peach puff",
"Peach-orange",
"Peach-yellow",
"Peachesncream",
"Peacoat",
"Peacock blue",
"Peak green",
"Pear",
"Pearl",
"Pearl Aqua",
"Pearl White",
"Pearly purple",
"Peridot",
"Periwinkle",
"Persian blue",
"Persian green",
"Persian indigo",
"Persian orange",
"Persian pink",
"Persian plum",
"Persian red",
"Persian rose",
"Persimmon",
"Peru",
"Petal",
"Pewter",
"Phlox",
"Phthalo blue",
"Phthalo green",
"Pictorial carmine",
"Piggy pink",
"Pine",
"Pine green",
"Pineapple",
"Pink",
"Pink Beige",
"Pink Cheetah",
"Pink Green",
"Pink Purple Green",
"Pink Sherbet",
"Pink indigo",
"Pink lace",
"Pink lavender",
"Pink light",
"Pink pearl",
"Pink-orange",
"Pinky",
"Pistachio",
"Platinum",
"Plum",
"Poppy",
"Popstar",
"Portland Orange",
"Powder blue",
"Princeton orange",
"Prune",
"Prussian blue",
"Psychedelic purple",
"Puce",
"Puce red",
"Pumpkin",
"Pure",
"Pure white",
"Purple",
"Purple Heart",
"Purple fuchsia",
"Purple light",
"Purple mountain majesty",
"Purple navy",
"Purple pizzazz",
"Purple taupe",
"Purple-Cream",
"Purple-pink",
"Purplish red",
"Purpureus",
"Putty",
"Quartz",
"Queen blue",
"Queen pink",
"Quicksilver",
"Rackley",
"Radical Red",
"Raisin",
"Rajah",
"Raspberry",
"Raspberry glace",
"Raspberry pink",
"Raspberry rose",
"Raw umber",
"Razzle dazzle rose",
"Razzmatazz",
"Razzmic Berry",
"Red",
"Red Clay",
"Red Hot",
"Red Pearl",
"Red black",
"Red devil",
"Red-brown",
"Red-orange",
"Red-violet",
"Redwood",
"Regalia",
"Resolution blue",
"Rhythm",
"Rich black",
"Rich brilliant lavender",
"Rich carmine",
"Rich electric blue",
"Rich lavender",
"Rich lilac",
"Rich maroon",
"Rifle green",
"Robin egg blue",
"Rocket metallic",
"Roman silver",
"Rose",
"Rose Bud",
"Rose Petal",
"Rose bonbon",
"Rose ebony",
"Rose gold",
"Rose madder",
"Rose pink",
"Rose quartz",
"Rose red",
"Rose red-light khaki",
"Rose taupe",
"Rose vale",
"Rosewood",
"Rosso corsa",
"Rosy brown",
"Royal",
"Royal azure",
"Royal blue",
"Royal fuchsia",
"Royal purple",
"Royal yellow",
"Ruber",
"Rubine red",
"Ruby",
"Ruby red",
"Ruddy",
"Ruddy brown",
"Ruddy pink",
"Rufous",
"Russet",
"Russian green",
"Russian violet",
"Rust",
"Rust brown",
"Rusty",
"Rusty red",
"Sacramento State green",
"Saddle",
"Saddle brown",
"Safety orange",
"Safety yellow",
"Saffron",
"Sage",
"Salmon",
"Salmon pink",
"Sand",
"Sand dune",
"Sandstone",
"Sandstorm",
"Sandy",
"Sandy brown",
"Sandy taupe",
"Sangria",
"Sap green",
"Sapphire",
"Sapphire blue",
"Satin sheen gold",
"Scarlet",
"Schauss pink",
"School bus yellow",
"Screamin' Green",
"Scuba Blue",
"Sea",
"Sea blue",
"Sea green",
"Seal brown",
"Seashell",
"Selective yellow",
"Sensual",
"Sepia",
"Serenity",
"Shadow",
"Shampoo",
"Shamrock green",
"Sheen Green",
"Shimmering Blush",
"Shocking pink",
"Sienna",
"Sigal",
"Silver",
"Silver Lake blue",
"Silver chalice",
"Silver gray",
"Silver green",
"Silver grey",
"Silver pink",
"Silver sand",
"Silver white",
"Sinopia",
"Skobeloff",
"Sky",
"Sky blue",
"Sky magenta",
"Skyblue Orange",
"Slate",
"Slate blue",
"Slate gray",
"Smalt",
"Smitten",
"Smoke",
"Smokey topaz",
"Smoky black",
"Snorkel Blue",
"Snow",
"Snow White",
"Soap",
"Sonic silver",
"Southern Moss",
"Space cadet",
"Spanish bistre",
"Spanish blue",
"Spanish carmine",
"Spanish crimson",
"Spanish gray",
"Spanish orange",
"Spanish sky blue",
"Spanish viridian",
"Sparkling White",
"Spartan Crimson",
"Spice Coral",
"Spiro Disco Ball",
"Spring bud",
"Spring green",
"St. Patrick's blue",
"Star",
"Star command blue",
"Steel",
"Steel Blue-Purple",
"Steel Gray",
"Steel blue",
"Steel pink",
"Stem",
"Stik-It",
"Stil de grain yellow",
"Stizza",
"Stone",
"Stonewash",
"Storm",
"Stormcloud",
"Straw",
"Strawberry",
"Sunglow",
"Sunray",
"Sunset",
"Sunset Kiss",
"Sunset Plum",
"Sunset orange",
"Sunshine",
"Super pink",
"Sweet Gold",
"Tan",
"Tangelo",
"Tangerine",
"Tangerine yellow",
"Tango Red",
"Tango pink",
"Tannin",
"Tarragon",
"Taupe",
"Taupe gray",
"Tea green",
"Tea rose",
"Teal",
"Teal blue",
"Teal deer",
"Teal green",
"Telemagenta",
"Terra cotta",
"Thistle",
"Thulian pink",
"Tickle Me Pink",
"Tiffany Blue",
"Tiger",
"Tiger print",
"Tiger's eye",
"Timberwolf",
"Titanium yellow",
"Tobacco",
"Tomato",
"Toolbox",
"Topaz",
"Tortoise",
"Tractor red",
"Transparent",
"Transparent Black",
"Transparent White",
"Transparent dark green",
"Transparent pink",
"Transparent red",
"Trolley Grey",
"Tropical rain forest",
"True Blue",
"Tufts Blue",
"Tulip",
"Tumbleweed",
"Tundra",
"Turkish rose",
"Turqberry",
"Turquoise",
"Turquoise black",
"Turquoise blue",
"Turquoise green",
"Turquoise-Purple",
"Tuscan",
"Tuscan brown",
"Tuscan red",
"Tuscan tan",
"Tuscany",
"Twilight lavender",
"Tyrian purple",
"UA blue",
"UA red",
"UCLA Blue",
"UCLA Gold",
"UFO Green",
"UP Forest green",
"UP Maroon",
"USAFA blue",
"USC Cardinal",
"USC Gold",
"UV purple",
"Ube",
"Ultra",
"Ultra pink",
"Ultramarine",
"Ultramarine blue",
"Umber",
"Unbleached silk",
"United Nations blue",
"Unmellow yellow",
"Upsdell red",
"Urobilin",
"Utah Crimson",
"Vanilla",
"Vanilla ice",
"Vegas gold",
"Velvet Touch Pink",
"Velvet Touch Purple",
"Velvet Touch Zebra",
"Venetian red",
"Vercafe",
"Verde",
"Verdigris",
"Vermilion",
"Veronica",
"Viola",
"Violet",
"Violet-blue",
"Violet-red",
"Viridian",
"Viridian green",
"Vivid auburn",
"Vivid burgundy",
"Vivid cerise",
"Vivid orchid",
"Vivid sky blue",
"Vivid tangerine",
"Vivid violet",
"Warm Yellow",
"Warm black",
"Warm white",
"Washed black",
"Water",
"Water blue",
"Water wave camouflage",
"Watermelon red",
"Waterspout",
"Wedgewood",
"Wenge",
"Wheat",
"White",
"White Dye Dip",
"White Glitter",
"White Swan",
"White gold",
"White smoke",
"Wild Strawberry",
"Wild Watermelon",
"Wild blue yonder",
"Wild orchid",
"Wildberry",
"Willow",
"Windsor tan",
"Wine",
"Wine dregs",
"Wine red",
"Wisteria",
"Wolf",
"Wood brown",
"Wow",
"Xanadu",
"Yale Blue",
"Yankees blue",
"Yellow",
"Yellow Orange",
"Yellow Pearl",
"Yellow camouflage",
"Yellow light",
"Yellow rose",
"Yellow-green",
"Zaffre",
"Zebra",
"Zebra print",
"Zinnwaldite brown",
"Zomp",
"unadulterrated life"]